s1=int(input("First Student Marks ="))
s2=int(input("Second Student Marks ="))
s3=int(input("Third Student Marks ="))
s4=int(input("Forth Student Marks ="))
s5=int(input("Fifth Student Marks ="))
list=['78','90','92','95','98']
print("List:",list)
print("Sorted List(decreasing order):")
list.sort(reverse=True)
print("List:",list)
